steps:
#Build the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us.gcr.io/modern-water-333516/myapp:$SHORT_SHA', '.',  '-f', 'Dockerfile']
    timeout: 180s

#Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us.gcr.io/modern-water-333516/myapp:$SHORT_SHA']


  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
     - '-c'
     - >
       gcloud beta deploy releases create rel-$(date +%y%m%d-%s)
       --delivery-pipeline=cloud-deploy-test
       --region=us-central1  --images=myapp-image=us.gcr.io/modern-water-333516/myapp:$SHORT_SHA
images:
     - us.gcr.io/modern-water-333516/myapp:$SHORT_SHA
