apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
 name: cloud-deploy-test
description: cloud deploy delivery pipeline
serialPipeline:
 stages:
 - targetId: dev
 - targetId: qa
 - targetId: prd
---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: dev
description: dev cluster
gke:
 cluster: projects/modern-water-333516/locations/us-central1-c/clusters/cluster-dev
---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: qa
description: qa cluster
gke:
 cluster: projects/modern-water-333516/locations/us-central1-c/clusters/cluster-qa
---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: prd
description: stage cluster
gke:
 cluster: projects/modern-water-333516/locations/us-central1-c/clusters/cluster-prod
